
import Head from 'next/head'
import styles from './Home.module.css'
import './globals.css'
import Link from 'next/link'
import {GoHomeFill} from 'react-icons/go'
import { TbHelpOctagon } from 'react-icons/tb'


export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html className={styles.container}>
      <Head>
      icons: [
        rel:'icon',
        type:'image/png',
        sizes: '32*32',
        url: './icon.png',
      ]
      </Head>
      
      <body>
        <div>
        <nav className={styles.navbar} style={{padding:'10pt 5pt 5pt 10pt'}}>
          <div style={{display:'flex'}}>
              <div style={{paddingTop:'5px'}}>
                <Link href="/">
                <GoHomeFill style={{color:'white', width:'23px', height:'23px'}}></GoHomeFill>
                </Link>
              </div>  
              <div style={{paddingLeft:'80%'}}>
              <Link href="/about" style={{textDecoration:'none'}}>
              <div style={{color:'white'}}>
                    <TbHelpOctagon style={{width:'25px', height:'35px', padding:'0'}}></TbHelpOctagon>
              </div>
              </Link>
              </div>
          </div>
        </nav>
        <main>
          {children}
        </main> 
        </div> 
      </body>
      
    </html>
  )
}
